services:
  directus:
    image: directus/directus:11.8.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extension:/directus/extensions/sentoo-directus-extension
    environment:
      SECRET: "ArJaAyK6QBp87M4HJpK8WHZukccZvN5"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "Test123!"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      EXTENSIONS_AUTO_RELOAD: true
